Repository the-monkeys/the_monkeys, pull requests merged in 2023-12, with the labels that each got.

#92 removed unwanted code and fixed the existing login and register image…
  src/components/Navigation/Navigation.jsx
  src/pages/Auth/components/Login/Login.jsx
  src/pages/Auth/components/Register/Register.jsx
  src/pages/Profile/Profile.jsx
  src/pages/write/editorComponent/EditorComponent.jsx
Labels: bug

#98 add: Terms of use page
  src/App.jsx
  src/components/Footer/Footer.js
  src/components/Footer/TermsOfUse.css
  src/components/Footer/TermsOfUse.js
Labels: Feature

#100 add: privacy policy page
  src/App.jsx
  src/components/Footer/Footer.js
  src/components/Footer/FooterComponent.css
  src/components/Footer/PrivacyPolicyPage.js
  src/components/Footer/TermsOfUse.js
Labels: enhancement, Feature

#101 Cookie policy page
  src/App.jsx
  src/components/Cookie/Cookie.jsx
  src/components/Footer/CookiePolicyPage.js
  src/components/Footer/Footer.js
Labels: bug, enhancement, Feature

#105 Exclamation added
  src/components/Contributors/Members.jsx
  src/components/Footer/FooterComponent.css
  src/components/Navigation/Navigation.jsx
  src/pages/Auth/components/Login/Login.jsx
  src/pages/Auth/components/Register/Register.jsx
  src/redux/auth/authSlice.js
  src/utils/Constant.js
Labels: bug, enhancement
